name: Yazio Export

on:
  workflow_dispatch: # manuell starten
  schedule:
    - cron: "0 6 * * *" # jeden Tag um 6 Uhr UTC

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Run Yazio Export
        run: node yazio-export.js
        env:
          N8N_WEBHOOK_URL: ${{ secrets.N8N_WEBHOOK_URL }}
          YAZIO_EMAIL: ${{ secrets.YAZIO_EMAIL }}
          YAZIO_PASSWORD: ${{ secrets.YAZIO_PASSWORD }}
